### ISSUE TITLE
MacOS as target cannot use brew

### ISSUE THREAD

**Issue by mark2185** [xxh/xxh-shell-bash#4]
**Local OS (where xxh is installed):** archlinux 6.2.5-arch1-1
**Destination host OS:** macOS ventura 13.1
**xxh version:** `xxh/0.8.12`
**xxh-plugins installed:** none explicitly

**Steps to Reproduce**
1. `xxh macLaptop +s bash`
2. The output log:
```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```
3. What is the problem
```
bash-3.2$ brew
bash: brew: command not found
```
4. `brew` should exist

I tried using `+zsh` but that doesn't even start, it throws a "cannot execute binary file" error, but I'll deal with that after I at least get `bash` working.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
If you have an access to Mac get the `brew` location:
```bash
which brew
# /opt/homebrew/bin/brew
echo $PATH
# ...:/opt/homebrew/bin:...
```
Then check the same in xxh session. If the path to brew is not in `$PATH` run:
```xsh
export PATH=/opt/homebrew/bin:$PATH
brew
```

**Comment by mark2185** [comment]
That did it, I added it to `~/.xxh/shells/xxh-shell-bash/build/bashrc`.

Thanks!
